# Generated by Django 5.1.7 on 2025-03-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('telefone', models.CharField(max_length=9, unique=True)),
                ('nacionalidade', models.CharField(default='Moçambicano', max_length=50)),
                ('residencia', models.CharField(blank=True, max_length=255)),
                ('proveniencia', models.CharField(blank=True, choices=[('SUR', 'Servico de Urgencia de Reanimacao'), ('PED', 'Pediatria'), ('CIR', 'Cirurgia'), ('GIN', 'Ginecologia'), ('OBST', 'Obstetricia'), ('UROL', 'Urologia'), ('MED_I', 'Medicina Homem'), ('MED_II', 'Medicina Mulher'), ('OFT', 'Oftalmologia'), ('C.EXT', 'Consulta Externa'), ('BS', 'Banco de Socorros'), ('AMB', 'Ambulatorio')], max_length=255)),
                ('historico_medico', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
