# Generated by Django 5.1.7 on 2025-03-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doador', models.CharField(max_length=255, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=9)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Sanguíneo',
                'verbose_name_plural': 'Tipos Sanguíneos',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_saco', models.CharField(max_length=255, unique_for_year=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('foi_adicionado_ao_estoque', models.BooleanField(default=False)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.doador')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueSangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_total', models.PositiveIntegerField(default=0)),
                ('tipo_sanguineo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blood_bank.tiposanguineo')),
            ],
            options={
                'verbose_name': 'Estoque de Sangue',
                'verbose_name_plural': 'Estoques de Sangue',
            },
        ),
        migrations.AddField(
            model_name='doador',
            name='tipo_sanguineo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blood_bank.tiposanguineo'),
        ),
    ]
